DROP DATABASE BACKEND_PROJETO;
CREATE DATABASE IF NOT EXISTS BACKEND_PROJETO;
USE BACKEND_PROJETO;

CREATE TABLE IF NOT EXISTS XS_PRODUTO(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOME_PRODUTO VARCHAR(20) NOT NULL,
  PONTO_REP_PRODUTO INT NOT NULL
  );

CREATE TABLE IF NOT EXISTS XS_FORNECEDOR(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOME_FORNECEDOR VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS XS_DEPOSITO(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOME_DEPOSITO VARCHAR(20) NOT NULL
);


CREATE TABLE IF NOT EXISTS XS_FORNECEDOR_PRODUTO(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ID_FORNECEDOR INT NOT NULL,
  ID_PRODUTO INT NOT NULL,
  CONSTRAINT FK_ID_FORNECEDOR FOREIGN KEY (ID_FORNECEDOR) REFERENCES XS_FORNECEDOR (id),
  CONSTRAINT FK_ID_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES XS_PRODUTO(id)
);

ALTER TABLE XS_FORNECEDOR_PRODUTO
  ADD INDEX IX_ID_FORNECEDOR (ID_FORNECEDOR),
  ADD INDEX IX_ID_PRODUTO (ID_PRODUTO);

CREATE TABLE IF NOT EXISTS XS_DEPOSITO_PRODUTO(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ID_DEPOSITO INT NOT NULL,
  ID_PRODUTO INT NOT NULL,
  PONTO_REP_DEPOSITO INT NOT NULL,
  CONSTRAINT FK_ID_DEPOSITO_DP FOREIGN KEY (ID_DEPOSITO) REFERENCES XS_DEPOSITO (id),
  CONSTRAINT FK_ID_PRODUTO_DP FOREIGN KEY (ID_PRODUTO) REFERENCES XS_PRODUTO (id)
);

ALTER TABLE XS_DEPOSITO_PRODUTO
  ADD INDEX IDX_ID_DEPOSITO_DP (ID_DEPOSITO),
  ADD INDEX IDX_ID_PRODUTO_DP (ID_PRODUTO);

CREATE TABLE IF NOT EXISTS XS_MOVIMENTACAO (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ID_DEPOSITO INT NOT NULL,
  ID_PRODUTO INT NOT NULL,
  PRECO_PRODUTO DECIMAL(6,2) NOT NULL,
  QTD_MOVIMENTACAO INT NOT NULL,
  TIPO_MOVIMENTACAO INT NOT NULL,
  CONSTRAINT FK_ID_DEPOSITO_M FOREIGN KEY (ID_DEPOSITO) REFERENCES XS_DEPOSITO (id),
  CONSTRAINT FK_ID_PRODUTO_M FOREIGN KEY (ID_PRODUTO) REFERENCES XS_PRODUTO (id)
);

ALTER TABLE XS_MOVIMENTACAO
  ADD INDEX IDX_ID_DEPOSITO_M (ID_DEPOSITO),
  ADD INDEX IDX_ID_PRODUTO_M (ID_PRODUTO);